A simple logistic model: log-odds of a purchase grows linearly with number of exposures to advertisement.

In [8]:
import numpy as np
from bokeh.plotting import figure
from bokeh.io import output_notebook,show
output_notebook()

Loading BokehJS ...

In [9]:
def sigma(n):
    return 1/(1+np.exp(-n))

In [10]:
def log_odds(a,b,x):
    return a*x+b

In [91]:
N=10

In [101]:
probs=[sigma(log_odds(.8,-8,x)) for x in range(N)]

In [102]:
f=np.random.binomial(100,probs)

In [103]:
f

array([ 0,  0,  0,  1,  1,  0,  4,  5, 21, 25])

In [104]:
g=figure(title='Conversion Percentage vs Ad Exposure')
g.quad(left=[x+.1 for x in list(range(N))],top=f,bottom=[0]*N,right=[x-.1 for x in list(range(1,N+1))])
show(g)

In [105]:
f

array([ 0,  0,  0,  1,  1,  0,  4,  5, 21, 25])

In [106]:
from sklearn.linear_model import LogisticRegression

In [107]:
P=LogisticRegression()

In [119]:
P.fit(np.arange(10).reshape(-1,1),np.array(f))

LogisticRegression()

In [120]:
P

LogisticRegression()

In [121]:
P.coef_

array([[-0.98361575],
       [-0.60220027],
       [-0.04629261],
       [ 0.20411746],
       [ 0.51242179],
       [ 0.91556938]])

In [118]:
np.arange(10).reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])