In [62]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from bokeh.plotting import Figure
from bokeh.io import output_notebook, show
output_notebook()

x=np.array([0,1,2,3,4,5,6,7,8,9,10])
y=3+x-x**2+10*x**3-3*x**4+np.random.normal(0,1,11)
f = PolynomialFeatures(3).fit_transform(np.transpose(x).reshape(-1,1))
Model=LinearRegression()
ModelR=Ridge(alpha=1000)
Model.fit(f,y)
ModelR.fit(f,y)
Model.intercept_

Loading BokehJS ...

218.11058923264864

In [63]:
f

array([[   1.,    0.,    0.,    0.],
       [   1.,    1.,    1.,    1.],
       [   1.,    2.,    4.,    8.],
       [   1.,    3.,    9.,   27.],
       [   1.,    4.,   16.,   64.],
       [   1.,    5.,   25.,  125.],
       [   1.,    6.,   36.,  216.],
       [   1.,    7.,   49.,  343.],
       [   1.,    8.,   64.,  512.],
       [   1.,    9.,   81.,  729.],
       [   1.,   10.,  100., 1000.]])

In [64]:
y

array([ 1.30411472e+00,  1.14308758e+01,  3.29831184e+01,  2.48409667e+01,
       -1.37987608e+02, -6.41787950e+02, -1.75449188e+03, -3.81186446e+03,
       -7.22161577e+03, -1.24604399e+04, -2.00859338e+04])

In [65]:
Model.coef_

array([   0.        , -747.94297015,  373.74254081,  -49.98241113])

In [66]:
np.matmul(f,Model.coef_)+Model.intercept_

array([ 2.18110589e+02, -2.06072251e+02, -1.82664477e+02, -1.15605544e+01,
        7.34504939e+00, -4.25842132e+02, -1.61101657e+03, -3.84807272e+03,
       -7.43690506e+03, -1.26774080e+04, -1.98694762e+04])

In [67]:
Model.predict(f)

array([ 2.18110589e+02, -2.06072251e+02, -1.82664477e+02, -1.15605544e+01,
        7.34504939e+00, -4.25842132e+02, -1.61101657e+03, -3.84807272e+03,
       -7.43690506e+03, -1.26774080e+04, -1.98694762e+04])

In [68]:
Fig=Figure()
Fig.scatter(x=[0,1,2,3,4,5,6,7,8,9,10],y=y)
Fig.line(x=[0,1,2,3,4,5,6,7,8,9,10],y=Model.predict(f))
Fig.line(x=[0,1,2,3,4,5,6,7,8,9,10],y=ModelR.predict(f),color='red')
show(Fig)

In [69]:
ModelR.coef_

array([  0.        ,  10.22621428,  48.06791034, -24.05987302])

In [70]:
Model.coef_

array([   0.        , -747.94297015,  373.74254081,  -49.98241113])