In [29]:
import pandas as pd
import numpy as np
from bokeh.plotting import figure
from bokeh.io import output_notebook, show
output_notebook()

Loading BokehJS ...

In [30]:
pwd

'/home/jet08013/GitHub/BookFun'

In [31]:
data = pd.read_csv('notebooks/data/Online_Shopping/online_shoppers_intention.csv')

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
M = LogisticRegression()

In [34]:
data.head()

Administrative  Administrative_Duration  ...  Weekend  Revenue
0               0                      0.0  ...    False    False
1               0                      0.0  ...    False    False
2               0                      0.0  ...    False    False
3               0                      0.0  ...    False    False
4               0                      0.0  ...     True    False

[5 rows x 18 columns]

In [35]:
data2=data[data['ProductRelated_Duration']<5000]

In [36]:
data2.shape

(11872, 18)

In [37]:
M.fit(data2['ProductRelated_Duration'].values.reshape(-1,1),data2['Revenue'])

LogisticRegression()

In [38]:
data2['ProductRelated_Duration'].describe()

count    11872.000000
mean       926.440995
std       1025.509431
min          0.000000
25%        173.187500
50%        558.705556
75%       1324.254166
max       4996.666667
Name: ProductRelated_Duration, dtype: float64

In [39]:
z=M.predict_proba(np.linspace(0,10000,100).reshape(-1,1))[:,1]

In [41]:
f=figure()
f.line(x=np.linspace(0,10000,100),y=z)
show(f)

In [42]:
data2['Revenue'].value_counts()

False    10119
True      1753
Name: Revenue, dtype: int64

In [28]:
(data2['Revenue']=='True').sum()

0

In [64]:
data2['r']=pd.cut(data2['ProductRelated_Duration'],bins=np.arange(0,5000,250),labels=[x for x in range(0,19)])

<ipython-input-64-c1653d5dd8a7>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['r']=pd.cut(data2['ProductRelated_Duration'],bins=np.arange(0,5000,250),labels=[x for x in range(0,19)])


In [65]:
summary=data2.groupby('r')['Revenue'].describe()

In [66]:
summary['prob']=1-summary['freq']/summary['count']

In [67]:
summary

count unique    top  freq      prob
r                                     
0   2971      2  False  2799  0.057893
1   1873      2  False  1628  0.130806
2   1331      2  False  1090  0.181067
3   1008      2  False   787  0.219246
4    767      2  False   605  0.211213
5    615      2  False   476  0.226016
6    506      2  False   425  0.160079
7    375      2  False   295  0.213333
8    332      2  False   260  0.216867
9    236      2  False   182  0.228814
10   220      2  False   161  0.268182
11   172      2  False   140  0.186047
12   136      2  False   101  0.257353
13   124      2  False   101  0.185484
14   106      2  False    78  0.264151
15    84      2  False    64  0.238095
16    84      2  False    67  0.202381
17    67      2  False    47  0.298507
18    55      2  False    36  0.345455

In [70]:
f=figure()
f.line(x=np.arange(19),y=summary['prob'])

GlyphRenderer(id='1840', ...)

In [71]:
show(f)

In [72]:
def sigma(x):
    return 1/(1+np.exp(-x))

In [78]:
x=np.linspace(-6,6,100)
y=sigma(x)
f=figure(title='Logistic Function')
f.line(x=x,y=y)
show(f)

In [79]:
def s2(x):
    return 1/(1+np.exp(-np.log(2)*x))

In [93]:
x=np.arange(-3,4,1)

In [94]:
x

array([-3, -2, -1,  0,  1,  2,  3])

In [95]:
s2(x)

array([0.11111111, 0.2       , 0.33333333, 0.5       , 0.66666667,
       0.8       , 0.88888889])

In [96]:
np.random.binomial(100,s2(x))

array([10, 18, 38, 50, 69, 78, 86])